const styles = {
  divSup  : {
    display : "flex",
    flexDirection     :   "row",
    justifyContent    :   "space-around",
    alignItems        :   "center",
    height            :   "25%",
    width             :   "100%"
  },
    imgCamp : {
      height          :   "90%",
      width           :   "10%",
      borderRadius    :   "150px",
      border          :   "1px solid aqua",
    },
    divCamp : {
      display         :   "flex",
      flexDirection   :   "row",
      justifyContent  :   "space-around",
      alignItems      :   "center",
      height          :   "100%",
      width           :   "90%",
    },
      title : {
        height        :   "auto",
        width         :   "40%",
        fontSize      :   "18px",
        color         :   "white",
        fontWeight    :   "bold",
      },
      btt : {
        height          :   "55%",
        width           :   "15%",
        fontSize        :   "20px",
        fontWeight      :   "bold",
        color           :   "white",
        borderRadius    :   "10px",
        border          :   "1.5px solid aqua",
      },
  divCab : {
    display         :   "flex",
    flexDirection   :   "row",
    justifyContent  :   "center",
    alignItems      :   "center",
    height          :   "10%",
    width           :   "100%",
    marginTop       :   "5px",
  },
  divInf  : {
    display           : "flex",
    flexDirection     :   "column",
    justifyContent    :   "flex-start",
    alignItems        :   "center",
    width             :   "100%",
    height            :   "75%",
    overflow          :   "auto",
  },
    divCompRkg : {
      display         :   "flex",
      flexDirection   :   "row",
      justifyContent  :   "center",
      alignItems      :   "center",
      height          :   "80px",
      width           :   "100%",
    },
      celula : {
        display         :   "flex",
        justifyContent  :   "center",
        alignItems      :   "center",
        height          :   "100%",
        width           :   "10%",
        fontSize        :   "20px",
        bordWidth       :   "1px",
        borderStyle     :   "solid",
        borderColor     :   "aqua",
        color           :   "white",
      },
      celulaG : {
        display         :   "flex",
        justifyContent  :   "center",
        alignItems      :   "center",
        height          :   "100%",
        width           :   "10%",
        fontSize        :   "20px",
        bordWidth       :   "1px",
        borderStyle     :   "solid",
        borderColor     :   "aqua",
        
      },
        imagem : {
          
          height        :   "70px",
          width         :   "70px",
        },
        txt : {
          fontSize      :   "18px",
          color         :   "white",
          fontWeight    :   "bold",
        }

} ; export default styles ;