const styles = {
  divInf:{
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    height: '70%',
    width: '100%',
  },
    divInputs:{
      height: '100%',
      width: '40%',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'flex-start',
      alignItems: 'center',
    },
      divJgdrs:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        height: '35%',
        width: '100%',
        marginTop: '2%',
        overflow: 'auto',
      },
        divJgdrSel:{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
          height: '100%',
          width: 'auto',
        },
          img:{
            height: '70%',
            width: 'auto',
            borderRadius: '60px',
            border: '2px solid white',
          },
          imgLb:{
            height: 'auto',
            width: '100%',
            fontSize: '22px',
            color: 'white',
            textAlign: 'center',
          },
    divFlat: {
      display         : "flex",
      flexDirection   : "column",
      justifyContent  : "flex-start",
      alignItems      : "center",
      height          : "100%",
      width           : "50%",
    },
      label: {
        height: '10%',
        width: '100%',
        textAlign: 'center',
        fontSize: 28,
        fontWeight: 'bold',
        color: '#fff',
        marginTop: 10,
        marginHorizontal: 10,
      },
      flat: {
        height: '88%',
        width: '100%',
        overflow: 'auto',
      } 
}; export default styles;